[package]
name = "test-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
f1-game-client = {path = "../f1-game-client"}
serde_repr = "0.1.16"
